### ISSUE TITLE
Ubuntu: Does not show First recovery Image in Dialog after Embryo creation

### ISSUE THREAD

**Issue by DavidMoersdorf** [alexblaessle/PyFRAP#11]
In the first Dialog after embryo creation (setting basic image information such as resolution and imaging depth) the "preview" image is not shown.

Traceback (most recent call last):
  File "/home/lin2-local/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_app.py", line 1235, in newEmbryo
    self.editEmbryo()
  File "/home/lin2-local/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_app.py", line 1285, in editEmbryo
    ret=pyfrp_gui_embryo_dialogs.embryoDialog(currEmbryo,self).exec_()
  File "/home/lin2-local/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_gui_embryo_dialogs.py", line 176, in __init__
    self.showFirstDataImg()
  File "/home/lin2-local/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_gui_embryo_dialogs.py", line 277, in showFirstDataImg
    img=pyfrp_img_module.loadImg(fnImg,self.embryo.dataEnc)
  File "/home/lin2-local/.local/lib/python2.7/site-packages/pyfrp/modules/pyfrp_img_module.py", line 688, in loadImg
    img = skimage.io.imread(fn).astype(enc)
  File "/usr/lib/python2.7/dist-packages/skimage/io/_io.py", line 97, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/skimage/io/_plugins/pil_plugin.py", line 34, in imread
    im = np.fromstring(im.tostring(), dtype)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

**Comment by alexblaessle** [comment]
This seems to be a problem with scikit-image (v10.1) and PIL. Upgrading it via

``` bash
pip install --upgrade scikit-image  
```

should solve the problem
