### ISSUE TITLE
After first basic canvas dialoge pyFRAP wizard stops

### ISSUE THREAD

**Issue by hpreiss** [alexblaessle/PyFRAP#13]
Traceback (most recent call last):
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\gui\pyfrp_app.py", line 1416, in openWizard
    self.newEmbryo()
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\gui\pyfrp_app.py", line 1243, in newEmbryo
    self.editGeometry()
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\gui\pyfrp_app.py", line 1590, in editGeometry
    ret=pyfrp_gui_geometry_dialogs.zebrafishDomeStageDialog(currEmbryo.geometry,self).exec_()
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\gui\pyfrp_gui_geometry_dialogs.py", line 245, in __init__
    super(zebrafishDomeStageDialog,self).__init__(geometry,parent)	
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\gui\pyfrp_gui_geometry_dialogs.py", line 136, in __init__
    self.drawGeometry()
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\gui\pyfrp_gui_geometry_dialogs.py", line 223, in drawGeometry
    self.geometry.plotGeometry(ax=self.ax,ann=self.ann)
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\subclasses\pyfrp_geometry.py", line 333, in plotGeometry
    domain.draw(ax=ax,color=color,ann=ann)
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\modules\pyfrp_gmsh_geometry.py", line 978, in draw
    ax=pyfrp_vtk_module.renderVTK(ax)
  File "C:\Users\hpreiss\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyfrp\modules\pyfrp_vtk_module.py", line 112, in renderVTK
    if renderer.GetRenderWindow()==None:
AttributeError: 'Axes3DSubplot' object has no attribute 'GetRenderWindow'

**Comment by alexblaessle** [comment]
This was due to a bug in domain.draw() calling the vtk renderer even though the backend was mpl. Fixed in commit https://github.com/alexblaessle/PyFRAP/commit/9868c2bd0008f1de641bd2b574bf95e5b893fcee .
