### ISSUE TITLE
readStlFile crashes if FRAPBoundarySelector is called before

### ISSUE THREAD

**Issue by alexblaessle** [alexblaessle/PyFRAP#15]
When calling 
```python

from pyfrp.modules import pyfrp_gmsh_IO_module
from pyfrp.modules import pyfrp_plot_module
import sys

sel=pyfrp_plot_module.FRAPBoundarySelector(fn=someImgFile)
c,r=sel.getResults()

d=pyfrp_gmsh_IO_module.readStlFile(someSTLfile)
d.draw(backend='vtk')
```	

I get 
```
Traceback (most recent call last):
  File "readStl.py", line 8, in <module>
    d=pyfrp_gmsh_IO_module.readStlFile(sys.argv[1])
  File "/usr/local/lib/python2.7/dist-packages/pyfrp/modules/pyfrp_gmsh_IO_module.py", line 514, in readStlFile
    mesh=meshstl.Mesh.from_file(fn)
  File "/usr/local/lib/python2.7/dist-packages/stl/stl.py", line 316, in from_file
    fh, mode=mode, speedups=speedups)
  File "/usr/local/lib/python2.7/dist-packages/stl/stl.py", line 85, in load
    name, data = cls._load_binary(fh, header, check_size=True)
  File "/usr/local/lib/python2.7/dist-packages/stl/stl.py", line 102, in _load_binary
    count, MAX_COUNT)
AssertionError: File too large, got 942551865 triangles which exceeds the maximum of 100000000
```

However, not calling the ``FRAPBoundarySelector`` prevents the crash and everything is fine. ``globals()`` and ``locals()`` are not altered in any significant way.

**Comment by alexblaessle** [comment]
Update, this error is also caused if ``embryo.geometry.plotGeometry`` is called beforehand. Looks like there is a problem whenever there is some sort of ``matplotlib`` instance being called beforehand.

**Comment by alexblaessle** [comment]
I analyzed the problem in detail in this issue https://github.com/WoLpH/numpy-stl/issues/52.
Calling ``stl.Mesh.from_file(...,speedups=False)`` without speedups seems to fix the problem.

Fixed in commit https://github.com/alexblaessle/PyFRAP/commit/f2348d307c6892a872122052571b9f20df3bfb49 .
