### ISSUE TITLE
Basic canvas Dialog error after clicking done 

### ISSUE THREAD

**Issue by Akinrinade** [alexblaessle/PyFRAP#20]
Error traceback below after clicking done basic canvas dialog. No pop-up(s) appear thereafter to continue.
Thanks

Traceback (most recent call last):
  File "/home/osboxes/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_app.py", line 1561, in openWizard
    ret=self.newEmbryo()
  File "/home/osboxes/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_app.py", line 1365, in newEmbryo
    ret=self.editEmbryo()
  File "/home/osboxes/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_app.py", line 1429, in editEmbryo
    self.updatePropBar()
  File "/home/osboxes/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_app.py", line 1137, in updatePropBar
    self.showObjPropsInBar(self.currObj)
  File "/home/osboxes/.local/lib/python2.7/site-packages/pyfrp/gui/pyfrp_app.py", line 1115, in showObjPropsInBar
    if isinstance(vars(obj)[str(item)],(int,float,str)) or vars(obj)[str(item)]==None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by alexblaessle** [comment]
Hi @Akinrinade , 

sorry for the late reply. Looks like an easy issue to fix. I am on it.

**Comment by alexblaessle** [comment]
Fixed this issue in commit https://github.com/alexblaessle/PyFRAP/commit/d1debcd830c76cf29f8023aca7f373dab913e267. Can you confirm?
